package com.iprogrammerr.foodcontroller.view.message

enum class Message {
    FOOD_DEFINITION_CHANGED, FOOD_DEFINITION_MOVED, PORTIONS_CHANGED, MEALS_CHANGED,
    MEAL_CHANGED, DELETE_DAY_CLICKED, DAY_DELETED, DAYS_CHANGED, GOALS_CHANGED
}