language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-28.0.0

before_install:
    - yes | sdkmanager "platforms;android-28"

before_script:
  - chmod +x gradlew

script: 
    - ./gradlew clean build
    - ./gradlew test
